export const REGISTER_WORKER_QUEUE_NAME = 'REGISTER_WORKER_QUEUE_NAME'
export const ON_COMPLETE_WORKER_QUEUE_NAME = 'ON_COMPLETE_WORKER_QUEUE_NAME'
export const REGISTER_WORKER_OPTIONS = 'REGISTER_WORKER_OPTIONS'
export const WORKER_OPTIONS = 'WORKER_OPTIONS'
